pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Cloning Repository'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }

    post {
        success {
            echo 'Application Deployed Successfully'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
    stage('Kubernetes Deploy') {

    steps {

        sh 'kubectl apply -f k8s/deployment.yaml'

        sh 'kubectl apply -f k8s/service.yaml'
        }
    }
}
